load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    srcs = glob([]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    # copts = ["-I./modules/common/include"],
    visibility = ["//visibility:public"]
)
