// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pb/server.proto

#include "pb/server.pb.h"
#include "pb/server.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace com {
namespace sekirocc {
namespace face_service {

static const char* FaceService_method_names[] = {
  "/com.sekirocc.face_service.FaceService/BatchDetect",
};

std::unique_ptr< FaceService::Stub> FaceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FaceService::Stub> stub(new FaceService::Stub(channel, options));
  return stub;
}

FaceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_BatchDetect_(FaceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FaceService::Stub::BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::com::sekirocc::face_service::BatchDetectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchDetect_, context, request, response);
}

void FaceService::Stub::experimental_async::BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchDetect_, context, request, response, std::move(f));
}

void FaceService::Stub::experimental_async::BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchDetect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>* FaceService::Stub::PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::com::sekirocc::face_service::BatchDetectResponse, ::com::sekirocc::face_service::BatchDetectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchDetect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>* FaceService::Stub::AsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchDetectRaw(context, request, cq);
  result->StartCall();
  return result;
}

FaceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FaceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FaceService::Service, ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FaceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::com::sekirocc::face_service::BatchDetectRequest* req,
             ::com::sekirocc::face_service::BatchDetectResponse* resp) {
               return service->BatchDetect(ctx, req, resp);
             }, this)));
}

FaceService::Service::~Service() {
}

::grpc::Status FaceService::Service::BatchDetect(::grpc::ServerContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace com
}  // namespace sekirocc
}  // namespace face_service

