// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pb/server.proto
#ifndef GRPC_pb_2fserver_2eproto__INCLUDED
#define GRPC_pb_2fserver_2eproto__INCLUDED

#include "pb/server.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace com {
namespace sekirocc {
namespace face_service {

// 人脸检测
class FaceService final {
 public:
  static constexpr char const* service_full_name() {
    return "com.sekirocc.face_service.FaceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::com::sekirocc::face_service::BatchDetectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>> AsyncBatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>>(AsyncBatchDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>> PrepareAsyncBatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>>(PrepareAsyncBatchDetectRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>* AsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::sekirocc::face_service::BatchDetectResponse>* PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::com::sekirocc::face_service::BatchDetectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>> AsyncBatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>>(AsyncBatchDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>> PrepareAsyncBatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>>(PrepareAsyncBatchDetectRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void BatchDetect(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>* AsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::sekirocc::face_service::BatchDetectResponse>* PrepareAsyncBatchDetectRaw(::grpc::ClientContext* context, const ::com::sekirocc::face_service::BatchDetectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_BatchDetect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status BatchDetect(::grpc::ServerContext* context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchDetect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDetect(::grpc::ServerContext* context, ::com::sekirocc::face_service::BatchDetectRequest* request, ::grpc::ServerAsyncResponseWriter< ::com::sekirocc::face_service::BatchDetectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_BatchDetect<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_BatchDetect() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::com::sekirocc::face_service::BatchDetectRequest* request, ::com::sekirocc::face_service::BatchDetectResponse* response) { return this->BatchDetect(context, request, response); }));}
    void SetMessageAllocatorFor_BatchDetect(
        ::grpc::experimental::MessageAllocator< ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* BatchDetect(
      ::grpc::CallbackServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* BatchDetect(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_BatchDetect<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_BatchDetect<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchDetect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchDetect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchDetect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_BatchDetect() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BatchDetect(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* BatchDetect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* BatchDetect(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BatchDetect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::com::sekirocc::face_service::BatchDetectRequest, ::com::sekirocc::face_service::BatchDetectResponse>* streamer) {
                       return this->StreamedBatchDetect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BatchDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchDetect(::grpc::ServerContext* /*context*/, const ::com::sekirocc::face_service::BatchDetectRequest* /*request*/, ::com::sekirocc::face_service::BatchDetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchDetect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::com::sekirocc::face_service::BatchDetectRequest,::com::sekirocc::face_service::BatchDetectResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_BatchDetect<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_BatchDetect<Service > StreamedService;
};

}  // namespace face_service
}  // namespace sekirocc
}  // namespace com


#endif  // GRPC_pb_2fserver_2eproto__INCLUDED
